### ISSUE TITLE
Show the same notification multiple times in a row

### ISSUE THREAD

**Issue by LeleDev** [JanStevens/angular-growl-2#110]
How to show the same notification multiple times in a row? At the moment, if the same notification is sent twice or more, nothing happens, until the first one is dismissed

**Comment by oarcher** [comment]
just use
app.config(['growlProvider', function(growlProvider) {
  growlProvider.onlyUniqueMessages(false);
}]);

see doc on http://janstevens.github.io/angular-growl-2/

**Comment by LeleDev** [comment]
Wonderful! Thank you!!!
