### ISSUE TITLE
onopen and onclose

### ISSUE THREAD

**Issue by pabloleone** [JanStevens/angular-growl-2#48]
I'm using onopen and onclose hooks, but after looking at the code I realise that hte version 0.7.0 downloaded using bower is not the last version. Those hooks are missing.

Could you tag a new version with the current code to download using bower?

Thanks,

**Comment by JanStevens** [comment]
New version includes onopen and onclose

**Comment by maeishoj** [comment]
well doesn't look like.. or i can't seem to find out... how do i assign a custom function onClose event?

**Comment by royerboat** [comment]
@maeishoj Take a look at the docs for info on hooking into onclose and onopen. http://janstevens.github.io/angular-growl-2/#config-message-callbacks

**Comment by maeishoj** [comment]
@royerboat  thanks a lot! I'm not sure how I didn't see that documentation page before! :/ odd.. I did however figure out where to place them just before you responded by looking at the code ;) 

I had assumed the onclose callback to be passed to the html tag, but makes sense to have it where it is. :)

Thanks a lot for your help!
