### ISSUE TITLE
Centered growl not positioned correctly (incl. fix)

### ISSUE THREAD

**Issue by starf** [JanStevens/angular-growl-2#63]
Because max-width=400px, margin-left should probably be -200px for centered positionings instead of -150px.

Greetings

.growl-container.growl-fixed.top-center {
  top: 10px;
  left: 50%;
  margin-left: -200px;
}
.growl-container.growl-fixed.bottom-center {
  bottom: 10px;
  left: 50%;
  margin-left: -200px;
}

**Comment by JanStevens** [comment]
Feel free to add a PR :+1:

**Comment by starf** [comment]
Going to try this later today, will be my first.

**Comment by JanStevens** [comment]
Great!

Just change the files in the src directory, looking forward!
