### ISSUE TITLE
wrong index initialization in destroyAllMessages function

### ISSUE THREAD

**Issue by Siggen** [JanStevens/angular-growl-2#66]
In version v0.7.3, the `destroyAllMessages` function is defined like this :

    this.destroyAllMessages = function (referenceId) {
      var messages = this.getAllMessages(referenceId), i = messages.length;
      for (i - 1; i >= 0; i--) {
        messages[i].destroy();
      }
      if (this.directives[referenceId]) {
        this.directives[referenceId].messages = [];
      }
    };

On the first loop, notice the `i - 1` statement which does nothing. Calling this method on an empty messages array will iterate one time and will raise an exception because `messages[0]` returns `undefined`.

I propose the following version :

    this.destroyAllMessages = function (referenceId) {
      var messages = this.getAllMessages(referenceId);
      for (var i = messages.length - 1; i >= 0; i--) {
        messages[i].destroy();
      }
      if (this.directives[referenceId]) {
        this.directives[referenceId].messages = [];
      }
    };

**Comment by royerboat** [comment]
I submitted a pull request to fix this. Hopefully it gets picked up.

**Comment by Siggen** [comment]
Thanks a lot !

**Comment by JanStevens** [comment]
Nice catch, I'll look at the MR :+1:

**Comment by Siggen** [comment]
That was quick, thanks :-)
