### ISSUE TITLE
Feature request: Return the configuration object on config methods

### ISSUE THREAD

**Issue by diosney** [JanStevens/angular-growl-2#72]
Right now I'm setting the global configuration as this:

      growlProvider.globalTimeToLive(5000);
      growlProvider.globalDisableIcons(true);

which reads awfully.

When doing:

      growlProvider
                .globalTimeToLive(5000)
                .globalDisableIcons(true);

It is triggering the following error:

    growlProvider.globalTimeToLive(...) is undefined

so it appears it is not retuning the `growlProvider` instance.

Can this be added so we can chain config setters?

**Comment by JanStevens** [comment]
Sure feel free to add a PR!

**Comment by diosney** [comment]
I'm on that right now :)

One question, though, should I have to build the library before submitting the PR?

**Comment by diosney** [comment]
Any updates on this?
