### ISSUE TITLE
Replace $timeout by $interval to allow tests with protractor

### ISSUE THREAD

**Issue by gregwym** [JanStevens/angular-growl-2#81]
Protractor wait for $timeout to finish before start testing. Growl ttl should use $interval instead, to enable protractor to validate the notification message. 

https://github.com/marcorinck/angular-growl/issues/43
angular/protractor#169

**Comment by k3v3n** [comment]
Any plan to fix this ?

**Comment by silbermm** [comment]
:+1:

**Comment by area** [comment]
This seems like a pretty obvious thing to do. Is there a reason you're hesitant, @JanStevens?
