### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by Sylox** [JanStevens/angular-growl-2#84]
Does anyone know what's going on here? I think binding is not working, right?

![bildschirmfoto 2015-04-20 um 23 03 55](https://cloud.githubusercontent.com/assets/1336504/7240498/a66888a2-e7b1-11e4-98a2-623b1f6c0090.png)

code:

    growl.warning("This adds a warn message");
    growl.info("This adds a info message");
    growl.success("This adds a success message");
    growl.error("This adds a error message");

**Comment by mujuni88** [comment]
I have the same issue. Can someone look into this

**Comment by asabirov** [comment]
Are you using angular-translate?

I fixed that case there https://github.com/JanStevens/angular-growl-2/commit/9df4e8136dc0fdf15a91c6a92d749b080183d7e5
