### ISSUE TITLE
Error in IE8 closing messages

### ISSUE THREAD

**Issue by sistemanick** [JanStevens/angular-growl-2#96]
Getting "TypeError: Object doesn't support this property or method" errors when closing messages.

I fixed it by replacing line 409 with the following:
var messages = this.getAllMessages(message.referenceId), index = -1;

for (var i in messages) index = (messages[i] == message) ? i : index;

**Comment by flippinjoe21** [comment]
Please submit a PR for this fix

**Comment by sistemanick** [comment]
For some reason I can't create a new branch. Emailed Github, awaiting reply.

**Comment by flippinjoe21** [comment]
You do not have push permissions to this repo.   Please fork the repo, and make your changes on your own account, then submit a PR from your fork

**Comment by sistemanick** [comment]
Well that's what I first tried, but every time I tried to "fork" (using the top-right button), it forks the old "marcorinck/angular-growl" project. Sorry completely new to this thing :)

**Comment by sistemanick** [comment]
Managed to create pull request... please check
